/*
 * SQL script that creates all the neccessary tables 
 * Oracle DataBase
 */

CREATE TABLE News(
  NEWS_ID NUMBER(20) NOT NULL,
  TITLE NVARCHAR2(30) NOT NULL,
  SHORT_TEXT VARCHAR2(100) NOT NULL,
  FULL_TEXT VARCHAR2(2000) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  MODIFICATION_DATE date NOT NULL,
  PRIMARY KEY (NEWS_ID)
);

CREATE SEQUENCE NEWS_SEQUENCE
  START WITH 1
  MINVALUE 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE Comments(
  COMMENT_ID NUMBER(20) NOT NULL,
  NEWS_ID NUMBER(20) NOT NULL,
  COMMENT_TEXT NVARCHAR2(100) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (COMMENT_ID),
  CONSTRAINT fk_Comments_CommentId_NewS FOREIGN KEY (NEWS_ID)
  REFERENCES News (NEWS_ID)
    ON DELETE CASCADE
);

CREATE SEQUENCE COMMENTS_SEQUENCE
  START WITH 1
  MINVALUE 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE Authors(
  AUTHOR_ID NUMBER(20) NOT NULL,
  AUTHOR_NAME NVARCHAR2(30) NOT NULL,
  EXPIRED TIMESTAMP,
  PRIMARY KEY (AUTHOR_ID)
);

CREATE SEQUENCE AUTHORS_SEQUENCE
  START WITH 1
  MINVALUE 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE Tags(
  TAG_ID NUMBER(20) NOT NULL,
  TAG_NAME NVARCHAR2(30) NOT NULL,
  PRIMARY KEY (TAG_ID)
);

CREATE SEQUENCE TAGS_SEQUENCE
  START WITH 1
  MINVALUE 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE Users(
  USER_ID NUMBER(20) NOT NULL,
  USER_NAME NVARCHAR2(50) NOT NULL,
  LOGIN VARCHAR2(30) NOT NULL,
  PASSWORD VARCHAR2(30) NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE SEQUENCE USERS_SEQUENCE
  START WITH 1
  MINVALUE 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE Roles(
  USER_ID NUMBER(20) NOT NULL,
  ROLE_NAME VARCHAR2(50) NOT NULL,  
  CONSTRAINT fk_Roles_UserId_Users FOREIGN KEY (USER_ID)
  REFERENCES Users (USER_ID)
    ON DELETE CASCADE 
);

CREATE TABLE News_Tags(
  NEWS_ID NUMBER(20) NOT NULL,
  TAG_ID NUMBER(20) NOT NULL,  
  CONSTRAINT fk_NewsTags_TagId_News FOREIGN KEY (NEWS_ID)
  REFERENCES News (NEWS_ID)
    ON DELETE CASCADE, 
  CONSTRAINT fk_NewsTags_TagId_Tags FOREIGN KEY (TAG_ID)
  REFERENCES Tags (TAG_ID)
    ON DELETE CASCADE
);

CREATE TABLE News_Authors(
  NEWS_ID NUMBER(20) NOT NULL,
  AUTHOR_ID NUMBER(20) NOT NULL,  
  CONSTRAINT fk_NewsAuthors_NewsId_News FOREIGN KEY (NEWS_ID)
  REFERENCES News (NEWS_ID)
    ON DELETE CASCADE, 
  CONSTRAINT fk_NewsAuthors_AuthorId_Authors FOREIGN KEY (AUTHOR_ID)
  REFERENCES Authors (AUTHOR_ID)
    ON DELETE CASCADE
);